export default [
    {
      "user_id": 12345,
      "username": "john_doe",
      "full_name": "John Doe",
      "email": "john@example.com",
      "age": 30,
      "location": "New York, USA",
      "interests": ["hiking", "photography", "cooking"],
      "registered": true,
      "last_login": "2023-08-31T10:00:00Z",
      "followers": 500,
      "following": 200,
      "profile_picture": "https://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg"
    },
  
    {
      "user_id": 98765,
      "username": "mike_jones",
      "full_name": "Mike Jones",
      "email": "mike@example.com",
      "age": 25,
      "location": "Chicago, USA",
      "interests": ["music", "sports", "coding"],
      "registered": true,
      "last_login": "2023-08-29T08:45:00Z",
      "followers": 300,
      "following": 100,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img2_thumb.jpg"
    },
    {
      "user_id": 24680,
      "username": "lisa_brown",
      "full_name": "Lisa Brown",
      "email": "lisa@example.com",
      "age": 32,
      "location": "Houston, USA",
      "interests": ["yoga", "gardening", "travel"],
      "registered": true,
      "last_login": "2023-08-28T20:15:00Z",
      "followers": 250,
      "following": 180,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img3.jpg"
    },
    {
      "user_id": 54321,
      "username": "jane_smith",
      "full_name": "Jane Smith",
      "email": "jane@example.com",
      "age": 28,
      "location": "Los Angeles, USA",
      "interests": ["travel", "reading", "painting"],
      "registered": true,
      "last_login": "2023-08-30T15:30:00Z",
      "followers": 800,
      "following": 150,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img1_thumb.jpg"
    },
    {
      "user_id": 13579,
      "username": "alex_wilson",
      "full_name": "Alex Wilson",
      "email": "alex@example.com",
      "age": 22,
      "location": "Miami, USA",
      "interests": ["fashion", "beach", "movies"],
      "registered": true,
      "last_login": "2023-08-27T12:30:00Z",
      "followers": 150,
      "following": 80,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img4.jpg"
    },
    {
      "user_id": 56789,
      "username": "emily_thompson",
      "full_name": "Emily Thompson",
      "email": "emily@example.com",
      "age": 29,
      "location": "Seattle, USA",
      "interests": ["hiking", "reading", "photography"],
      "registered": true,
      "last_login": "2023-08-26T17:20:00Z",
      "followers": 450,
      "following": 300,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img5_thumb.jpg"
    },
    {
      "user_id": 11223,
      "username": "david_clark",
      "full_name": "David Clark",
      "email": "david@example.com",
      "age": 27,
      "location": "San Francisco, USA",
      "interests": ["technology", "gaming", "cooking"],
      "registered": true,
      "last_login": "2023-08-25T09:10:00Z",
      "followers": 600,
      "following": 400,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg"
    },
    {
      "user_id": 990088,
      "username": "sara_williams",
      "full_name": "Sara Williams",
      "email": "sara@example.com",
      "age": 31,
      "location": "Boston, USA",
      "interests": ["writing", "travel", "history"],
      "registered": true,
      "last_login": "2023-08-24T14:05:00Z",
      "followers": 280,
      "following": 220,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img6.jpg"
    },
    {
      "user_id": 665544,
      "username": "peter_smith",
      "full_name": "Peter Smith",
      "email": "peter@example.com",
      "age": 34,
      "location": "Denver, USA",
      "interests": ["hiking", "music", "fitness"],
      "registered": true,
      "last_login": "2023-08-23T19:50:00Z",
      "followers": 380,
      "following": 150,
      "profile_picture": "https://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg"
    },
    {
      "user_id": 778899,
      "username": "olivia_johnson",
      "full_name": "Olivia Johnson",
      "email": "olivia@example.com",
      "age": 26,
      "location": "Austin, USA",
      "interests": ["art", "cooking", "movies"],
      "registered": true,
      "last_login": "2023-08-22T11:40:00Z",
      "followers": 320,
      "following": 180,
      "profile_picture": "http://sorgalla.com/jcarousel/examples/_shared/img/img5_thumb.jpg"
    }
  ]
  